### PR TITLE
Remove verification code from email subjects.

### PR DESCRIPTION
**Pull request by fisx**
let's try this again, this time after reading the docs...

### CODE REVIEW

**Comment by lipis** [comment]
I think I found the mistake.. 

You are updating the `dist` folder, which is autogenerated.


Update the subject here: 
https://github.com/wireapp/wire-emails/blob/master/src/pages/en/user/email/verification.html#L2

**Comment by fisx** [comment]
i should have wondered about the path, thanks!  (hum, so we render the text versions from the html versions mechanically?  cool!)

**Comment by fisx** [comment]
(could we not have `dist` under git control somehow?  that would have helped avoid my confusion.)

**Comment by lipis** [comment]
The dist is needed to be there, because that's what the backend is getting as a source.

**Pull request merged**
